[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Build do Sanity Studio (removido - build feito localmente)
# [context.production]
#   command = "npm run build && cd studio && npm run build"

# Sanity Studio agora é gerenciado pelo Next.js
# (página de redirecionamento em app/studio/page.tsx)

# Redirect global para SPA (deve vir por último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de headers
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 