title: "Alexandre Guimarães - Palestrante e Consultor em IA"
description: "Especialista em Inteligência Artificial, Transformação Digital e Inovação. Palestras, workshops e consultoria em IA."
url: "https://www.aleguimas.com.br"
author: "Alexandre Guimarães"
email: "contato@aleguimas.com.br"
social:
  linkedin: "https://www.linkedin.com/in/alexandre-guimarães"
  youtube: "https://www.youtube.com/@aleguimas"
  instagram: "https://www.instagram.com/aleguimas"
  twitter: "https://twitter.com/aleguimas"
