# Decap CMS - Configuração Ultra-Simples
backend:
  name: git-gateway
  branch: main
  repo: aleguimas/site-aleguimas

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

site_url: https://www.aleguimas.com.br
display_url: https://www.aleguimas.com.br

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Resumo"
        name: "excerpt"
        widget: "text"
        required: true
      - label: "Data"
        name: "date"
        widget: "datetime"
        required: true
      - label: "Autor"
        name: "author"
        widget: "string"
        required: true
      - label: "Imagem de Capa"
        name: "cover"
        widget: "image"
        required: false
      - label: "Categoria"
        name: "category"
        widget: "select"
        options:
          - "Tecnologia"
          - "Inovação"
          - "Liderança"
          - "Estratégia"
        required: true
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Conteúdo"
        name: "body"
        widget: "markdown"
        required: true

workflow:
  - label: "Rascunho"
    name: "draft"
    color: "#ffeb3b"
  - label: "Pronto para Publicar"
    name: "ready"
    color: "#4caf50"
  - label: "Publicado"
    name: "published"
    color: "#2196f3"

preview_path: "blog/{{slug}}"
preview_path_date_field: "date"

locale: "pt"
