# Configuração Ultra-Simples do CMS
backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Resumo"
        name: "excerpt"
        widget: "text"
        required: true
      - label: "Data"
        name: "date"
        widget: "datetime"
        required: true
      - label: "Autor"
        name: "author"
        widget: "string"
        required: true
      - label: "Conteúdo"
        name: "body"
        widget: "markdown"
        required: true

workflow:
  - label: "Rascunho"
    name: "draft"
    color: "#ffeb3b"
  - label: "Publicado"
    name: "published"
    color: "#4caf50"
